training:
  epochs: 5
  lr: 0.01
  device: cpu

dataset:
  steps: 2000

dataloader:
  batch_size: 1
  num_workers: 8
  pin_memory: false
  drop_last: true

model:
  e1:
    synapse:
      out_features: 500
      bias: false
    neuron:
      dynamics:
        leak_i: [-100.0, 0]
        leak_v: [-100.0, 0]
        thresh: [1.0, 0.5]
      learnable: [leak_i, leak_v, thresh]
      spike_fn:
        name: ArcTan
        shape: [1.0, 10.0]
  e2:
    synapse:
      out_features: 500
      bias: false
    neuron:
      dynamics:
        leak_i: [-100.0, 0]
        leak_v: [-100.0, 0]
        thresh: [1.0, 0.5]
      learnable: [leak_i, leak_v, thresh]
      spike_fn:
        name: ArcTan
        shape: [1.0, 10.0]
  e3:
    synapse:
      out_features: 30
      bias: false
    neuron:
      dynamics:
        leak_i: [-100.0, 0]
        leak_v: [-100.0, 0]
        thresh: [1.0, 0.5]
      learnable: [leak_i, leak_v, thresh]
      spike_fn:
        name: ArcTan
        shape: [1.0, 10.0]
